# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e561d4e8ebf4d65a8f9f745734bc18cc82e0d73d8a11de04216546950a89ac2969d37a34e36c773e88ba6e566e854f3bba658849b8f838d48aa694db6229c3d5

test:
  secret_key_base: 02d0e1230cc1e718ce7a4097d5358cce0920c1aba1d04258e3be5a7a12281f9b7e9345333e154b550c54326e4ddf864553addaa6aef579db7fad214b706da393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
